import merch1 from "../assets/img/png/merch1.png"
import merch2 from "../assets/img/png/merch2.png"
import merch3 from "../assets/img/png/merch3.png"
import merch4 from "../assets/img/png/merch4.png"

export const productsList = [
  {
    id: 1,
    seo_title: "product_1",
    name: "Product 1",
    actual_price: "₹4999",
    price: "₹800",
    image: merch1,
    images: [merch1, merch4, merch3, merch2],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    quantity: 1,
    in_cart: false,
    total: 0,
    color: ["red", "blue", "green", "yellow"],
    size: ["S", "M", "L", "XL"],
    size_not_in_stock: ["S", "M"],
    discount: "20% OFF",
  },
  {
    id: 2,
    seo_title: "product_2",
    name: "Product 2",
    actual_price: "₹4999",
    price: "₹600",
    image: merch2,
    images: [merch1, merch4, merch3, merch2],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    quantity: 1,
    in_cart: false,
    total: 0,
    color: ["red", "blue", "green", "yellow"],
    size: ["S", "M", "L", "XL"],
    size_not_in_stock: ["S", "M"],
    discount: "FLASH SALE",
  },
  {
    id: 3,
    seo_title: "product_3",
    name: "Product 3",
    actual_price: "₹4999",
    price: "₹900",
    image: merch3,
    images: [merch1, merch4, merch3, merch2],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    quantity: 1,
    in_cart: false,
    total: 0,
    color: ["red", "blue", "green", "yellow"],
    size: ["S", "M", "L", "XL"],
    size_not_in_stock: ["S", "M"],
    discount: "WEEKEND SPECIAL",
  },
  {
    id: 4,
    seo_title: "product_4",
    name: "Product 4",
    actual_price: "₹4999",
    price: "₹499",
    image: merch4,
    images: [merch1, merch4, merch3, merch2],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    quantity: 1,
    in_cart: false,
    total: 0,
    color: ["red", "blue", "green", "yellow"],
    size: ["S", "M", "L", "XL"],
    size_not_in_stock: ["S", "M"],
    discount: "FOR YOU",
  },
  {
    id: 5,
    seo_title: "product_5",
    name: "Product 5",
    actual_price: "₹4999",
    price: "₹699",
    image: merch2,
    images: [merch1, merch4, merch3, merch2],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    quantity: 1,
    in_cart: false,
    total: 0,
    color: ["red", "blue", "green", "yellow"],
    size: ["S", "M", "L", "XL"],
    size_not_in_stock: ["S", "M"],
    discount: "FLASH SALE",
  },
  {
    id: 6,
    seo_title: "product_6",
    name: "Product 6",
    actual_price: "₹4999",
    price: "₹799",
    image: merch3,
    images: [merch1, merch4, merch3, merch2],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    quantity: 1,
    in_cart: false,
    total: 0,
    color: ["red", "blue", "green", "yellow"],
    size: ["S", "M", "L", "XL"],
    size_not_in_stock: ["S", "M"],
    discount: "50% OFF",
  },
]
